### ISSUE TITLE
Leftover char during autofix

### ISSUE THREAD

**Issue by nemaniarjun** [duaraghav8/Ethlint#221]
Hey! 
I recently wrote a core rule for linebreaks-style (https://github.com/duaraghav8/Solium/pull/220)

While testing out the rule I ran into an issue where the last char of the original file is added as the last char of the fixed files.

Since I am working with line endings this is a huge problem.
Truncated Examples for clarity (JSON.stringified)
input: 
```"CappedToken(_cap)\r\n    public\r\n  {}\r\n}\r\n"```

output given to fixer.replaceText(node, convertedTxt);
convertedTxt: 
```"CappedToken(_cap)\n    public\n  {}\n}\n"```

But the "fixed" string is actually: 
```"CappedToken(_cap)\n    public\n  {}\n}\n\r\n"```

Notice the extra `\r\n`

I traced the problem to the following line
https://github.com/duaraghav8/Solium/blob/b2a0c226f6d013524ab2b74f5d2116f71e4150eb/lib/autofix/source-code-fixer.js#L77

Since I am trying to replace the whole file, this line again adds a invalid line ending. 
As the user runs --fix multiple times, uselessly blank lines would be added.

Please fix this bug, or I can take this up if I have time.

**Comment by duaraghav8** [comment]
UPDATE: Turns out that this isn't an issue at all.

- To start, the method `fixer.replaceText(<node>, <text>)` was used in the `linebreak-style` rule's `fix()`. Here, the node supplied was the `ProgramNode`.
- The expectation was that this would replace the entire code because `ProgramNode` encompasses everything. But this is not the case. `ProgramNode` only encompasses till the closing brace `}` of the last declaration in the code file. This means any whitespace AFTER that last brace is not accounted for by ProgramNode, which is correct behaviour on the parser's end.
- Because of this, the actual length of the code could be more than the `start` and `end` position recorded by `ProgramNode`. Example:

```
contract Foo {}
contract Bar {
    ...
}



```

There is extra whitespace below the last declaration (`contract Bar`) in the above code. This space is NOT recorded as part of code by ProgramNode.

Hence, when we ask the linter's fixer to replace the ProgramNode's text with our text, it actually does not replace the contents of the whole file.

---

All in all, the only change that needed to be made was to use `fixer.replaceTextRange([0, txt.length], convertedTxt)` instead of `replaceText` to guarantee that entire contents of the file were replaced by the new code.

See commit https://github.com/duaraghav8/Ethlint/commit/ddb2a3cf5d136ad37166ad81092592de9626ca48
